CREATE TABLE users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(20)  NOT NULL,
    lastname  VARCHAR(20)  NOT NULL,
    email     VARCHAR(120) NOT NULL,
    password  VARCHAR(120) NOT NULL,
    role      VARCHAR(255) CHECK (role IN ('ADMIN', 'MANAGER', 'WAREHOUSEMAN', 'DRIVER', 'USER'))
);

CREATE TABLE token
(
    id         BIGSERIAL PRIMARY KEY,
    token      VARCHAR(255) UNIQUE NOT NULL,
    token_type VARCHAR(50)         NOT NULL,
    expired    BOOLEAN             NOT NULL DEFAULT FALSE,
    revoked    BOOLEAN             NOT NULL DEFAULT FALSE,
    user_id    BIGINT              NOT NULL,

);

CREATE TABLE warehouse
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_location VARCHAR(255) NOT NULL CHECK (warehouse_location IN ('Warsaw', 'Krakow', 'Rzeszow')),
    user_id            BIGINT
);

CREATE TABLE items
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(50) NOT NULL,
    item_code     VARCHAR(50) NOT NULL,
    quantity      INTEGER     NOT NULL,
    location_code VARCHAR(50),
    user_id       BIGINT      NOT NULL,
    warehouse_id  BIGINT
);

CREATE TABLE delivery
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier           VARCHAR(50) NOT NULL,
    date               DATE,
    number_delivery    VARCHAR(255),
    item_name          VARCHAR(255),
    item_code          VARCHAR(255),
    quantity           INTEGER     NOT NULL,
    delivery_status    VARCHAR(255) CHECK (delivery_status IN ('CREATED', 'IN_PROGRESS', 'DELIVERED', 'CANCELLED')),
    warehouse_location VARCHAR(255) CHECK (warehouse_location IN ('Warsaw', 'Krakow', 'Rzeszow')),
    user_id            BIGINT,
    item_id            BIGINT
);

ALTER TABLE token
    ADD CONSTRAINT fk_token_user FOREIGN KEY (user_id) REFERENCES users (id)

ALTER TABLE warehouse
    ADD CONSTRAINT fk_warehouse_user FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE items
    ADD CONSTRAINT fk_items_user FOREIGN KEY (user_id) REFERENCES users,
    ADD CONSTRAINT fk_items_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouse;

ALTER TABLE delivery
    ADD CONSTRAINT fk_delivery_user FOREIGN KEY (user_id) REFERENCES users,
    ADD CONSTRAINT fk_delivery_item FOREIGN KEY (item_id) REFERENCES items;

INSERT INTO users (firstname, lastname, email, password, role)
values ("Admin", "Admin", "admin@maghouse.pl", "admin", "ADMIN")