spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/maghouse
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  config:
    import:
      classpath: properties.secret
