spring:
  application:
    name: user-service
  profiler:
    active: default

server:
  port: 8080

cloud:
  discovery:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka