CREATE TABLE IF NOT EXISTS users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(20)  NOT NULL,
    lastname  VARCHAR(20)  NOT NULL,
    email     VARCHAR(120) NOT NULL UNIQUE,
    password  VARCHAR(120) NOT NULL,
    role      VARCHAR(255) CHECK (role IN ('ADMIN', 'MANAGER', 'WAREHOUSEMAN', 'DRIVER', 'USER'))
    );

CREATE TABLE IF NOT EXISTS token
(
    id         BIGSERIAL PRIMARY KEY,
    token      VARCHAR(255) UNIQUE NOT NULL,
    token_type VARCHAR(50)         NOT NULL,
    expired    BOOLEAN             NOT NULL DEFAULT FALSE,
    revoked    BOOLEAN             NOT NULL DEFAULT FALSE,
    user_Id    BIGINT              NOT NULL
    );

CREATE TABLE IF NOT EXISTS warehouse
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_location  VARCHAR(255) NOT NULL CHECK (warehouse_location IN ('Warsaw', 'Krakow', 'Rzeszow')),
    user_id            BIGINT NOT NULL
    );

CREATE TABLE IF NOT EXISTS items
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(50) NOT NULL,
    item_code      VARCHAR(50) NOT NULL,
    quantity      INTEGER     NOT NULL,
    location_code  VARCHAR(50),
    user_id       BIGINT,
    warehouse_id  BIGINT
    );

CREATE TABLE IF NOT EXISTS delivery
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier           VARCHAR(50) NOT NULL,
    date               DATE,
    number_delivery     VARCHAR(255),
    item_name           VARCHAR(255),
    item_code           VARCHAR(255),
    quantity           INTEGER     NOT NULL,
    delivery_status     VARCHAR(255) CHECK (delivery_status IN ('CREATED', 'IN_PROGRESS', 'DELIVERED', 'CANCELLED')),
    warehouse_location  VARCHAR(255) CHECK (warehouse_location IN ('Warsaw', 'Krakow', 'Rzeszow')),
    user_id            BIGINT,
    item_id            BIGINT
    );

ALTER TABLE token
    ADD CONSTRAINT fk_token_user FOREIGN KEY (user_Id) REFERENCES users (id);

ALTER TABLE warehouse
    ADD CONSTRAINT fk_warehouse_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE items
    ADD CONSTRAINT fk_items_user FOREIGN KEY (user_id) REFERENCES users (id),
    ADD CONSTRAINT fk_items_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouse (id);

ALTER TABLE delivery
    ADD CONSTRAINT fk_delivery_user FOREIGN KEY (user_id) REFERENCES users (id),
    ADD CONSTRAINT fk_delivery_item FOREIGN KEY (item_id) REFERENCES items (id);

INSERT INTO users (firstname, lastname, email, password, role) VALUES (
'Admin', 'Admin', 'admin@maghouse.pl', '$2a$10$hnGvBpLjNyfjELnUWkMHh.5skUmiv2luEElKtIZdQPmJR9SuuFC.i', 'ADMIN');

INSERT INTO warehouse (warehouse_location, user_id) VALUES ('Rzeszow', 1)
    ON CONFLICT (id) DO NOTHING;

INSERT INTO items (name, item_code, quantity, location_code, user_id, warehouse_id)
VALUES ('Screw', '1234-05-234-1234', 1500, 'RS01A', 1, 1 )
    ON CONFLICT (id) DO NOTHING;
